"""initial

Revision ID: b8659cc98002
Revises: 
Create Date: 2026-06-30 20:30:57.665637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8659cc98002'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.JSON(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=False),
    sa.Column('final_report', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_audits_video_id'), 'video_audits', ['video_id'], unique=True)
    op.create_table('compliance_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_audit_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['video_audit_id'], ['video_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_issues')
    op.drop_index(op.f('ix_video_audits_video_id'), table_name='video_audits')
    op.drop_table('video_audits')
    # ### end Alembic commands ###
